### PR TITLE
Introduce ForceFormatting

### PR DESCRIPTION
**Pull request by itzg**
I'm hoping I didn't step on any work you had in progress, but wanted to take a stab at #7 and put in the groundwork for #8 .

### CODE REVIEW

**Comment by x-cray** [comment]
@itzg I actually started work on #7 and #8 yesterday =) I'll take a look at your approach, however I can't guarantee that this PR could be merged, I also did some refactoring of the original code.

**Comment by itzg** [comment]
...yes, I see you're definitely in-progress https://github.com/x-cray/logrus-prefixed-formatter/tree/develop, so feel free to close this PR.

**Comment by itzg** [comment]
@x-cray I was just wondering if you've made any progress?

**Comment by x-cray** [comment]
@itzg Sorry for not picking up this for so long, busy work schedule. Yes, I have some uncommitted intermediate changes which I want to finalise. Hope to commit today.

**Comment by itzg** [comment]
@x-cray a gentle ping, but also wondering if you'd like me to point a PR at the `develop` branch to blend with your ongoing changes?

**Comment by x-cray** [comment]
I've implemented those changes in #13. Closing this PR.

**Comment by itzg** [comment]
Awesome, thanks

**Comment by x-cray** [comment]
Again, sorry for waiting

**Pull request closed without merging**
